name: Test

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      # TODO: fix peer dependencies
      - name: Install peer dependencies
        run: npm install react@^18.2.0 react-scripts@^5.0.1 --force
      - name: Test
        run: npm test
